from main_character.character import MainCharacter
Character = MainCharacter()
# Character.set_class_assassin()
# Character.set_class_warrior()
Character.add_level()
Character.add_strength()
Character.add_agility()
# Character.add_vitality()
Character.add_endurance()
Character.set_max_health()
Character.set_max_stamina()
print(Character.get_bars())
print(Character.get_parameters())
print(Character.get_combat_stats())
